Repository microsoft/cpp_client_telemetry, pull requests merged in 2021-05, with the labels that each got.

#851 Consolidate MSBuild Scripts
  build-Win32Debug.bat
  build-Win32Release.bat
  build-all.bat
  build-x64Debug.bat
  build-x64Release.bat
  tools/RunMsBuild.bat
  tools/RunTests.bat
Labels: P2, build infra

#852 win32-dll.vcxproj should consume products of win32-lib.vcxproj, not rebuild all CPP files therein.
  Solutions/win32-dll/win32-dll.vcxproj
Labels: P2, build infra

#860 Update cpp-start-windows.md
  docs/cpp-start-windows.md
Labels: build infra, documentation

#843 Ensure config headers are included once
  lib/include/mat/config-MIP.h
  lib/include/mat/config-MSIPC.h
  lib/include/mat/config-compact-dll.h
  lib/include/mat/config-compact-exp.h
  lib/include/mat/config-compact-min.h
  lib/include/mat/config-compact-noutc.h
  lib/include/mat/config-compact.h
  lib/include/mat/config-default-cs4.h
  lib/include/mat/config-default.h
  lib/include/mat/config-net40.h
  lib/include/mat/config-versionPrefix.h
Labels: build infra

#857 Set the NOMINMAX Macro in the Build
  CMakeLists.txt
  Solutions/net40/net40.vcxproj
  Solutions/win10-cs/win10-cs.vcxproj
  Solutions/win10-dll/win10-dll.vcxproj
  Solutions/win10-lib/win10-lib.vcxproj
  Solutions/win32-dll/win32-dll.vcxproj
  Solutions/win32-lib/win32-lib.vcxproj
  lib/api/CorrelationVector.cpp
  lib/decoder/PayloadDecoder.cpp
  lib/tracing/api/DebugLogger.hpp
Labels: OTEL, P3, build infra, design

#810 Updating mstelemetry portfile for windows
  tools/ports/mstelemetry/portfile.cmake
  tools/ports/mstelemetry/v142-build.patch
Labels: build infra

#874 Allow to specify any custom prefix with SetType API
  Solutions/MSTelemetrySDK.sln
  lib/api/Logger.cpp
  lib/api/Logger.hpp
  lib/config/RuntimeConfig_Default.hpp
  lib/include/public/ILogConfiguration.hpp
  tests/functests/APITest.cpp
Labels: P1, Teams

#875 Add configuration example that includes A/B EXP feature
  lib/include/mat/config-default-exp.h
Labels: Teams

#882 Support `any` (recent) Visual Studio version and any `PlatformToolset` version
  Solutions/MSTelemetrySDK.sln
  Solutions/before.targets
  Solutions/win10-cs/win10-cs.vcxproj
  Solutions/win10-lib/win10-lib.vcxproj
  Solutions/win32-lib/win32-lib.vcxproj
  Solutions/win32-mini-dll/win32-mini-dll.vcxproj
  Solutions/win32-mini-lib/win32-mini-lib.vcxproj
  build-all.bat
  build-win.ps1
  examples/c/SampleC/SampleC.vcxproj
  examples/cpp/SampleCpp/SampleCpp.vcxproj
  examples/cpp/SampleCppLogManagers/SampleCppLogManagers.vcxproj
  examples/cpp/SampleCppMini/SampleCppMini.vcxproj
  examples/cpp/SampleCppUWP/SampleCppUWP.vcxproj
  googletest/googlemock/msvc/2010/gmock.vcxproj
  googletest/googlemock/msvc/2010/gmock_main.vcxproj
  googletest/googlemock/msvc/2010/gmock_test.vcxproj
  googletest/googlemock/msvc/2015/gmock.vcxproj
  googletest/googlemock/msvc/2015/gmock_main.vcxproj
  googletest/googlemock/msvc/2015/gmock_test.vcxproj
  googletest/googletest/msvc/gtest.vcxproj
  sqlite/sqlite.vcxproj
  sqliteUWP/sqlite-uwp.vcxproj
  tests/functests/FuncTests.vcxproj
  tests/unittests/UnitTests.vcxproj
  tools/build-deps.cmd
  tools/ports/mstelemetry/v142-build.patch
  zlib/contrib/vstudio/vc14/zlibvc.vcxproj
Labels: build infra

#877 Update Status.java to fix EALREADY
  lib/android_build/maesdk/src/main/java/com/microsoft/applications/events/Status.java
Labels: Surface Duo
