Repository microsoft/cpp_client_telemetry, pull requests merged in 2021-07, with the labels that each got.

#893 Add CI for dev branch
  .github/workflows/build-android.yml
  .github/workflows/build-ios-latest.yml
  .github/workflows/build-posix-latest.yml
  .github/workflows/build-windows-clang.yaml.off
  .github/workflows/build-windows-vs2017.yaml.off
  .github/workflows/build-windows-vs2019.yaml
  .github/workflows/test-android-mac.yml
  .github/workflows/test-win-latest.yml
Labels: v4

#898 Obj-C Wrapper Updates
  wrappers/obj-c/ODWEventProperties.h
  wrappers/obj-c/ODWEventProperties.mm
  wrappers/obj-c/ODWLogManager.h
  wrappers/obj-c/ODWLogger.mm
  wrappers/obj-c/ODWPrivacyGuardInitConfig.h
  wrappers/obj-c/main.mm
Labels: iOS

#900 Add Reset Privacy Guard API
  wrappers/obj-c/ODWPrivacyGuard.h
  wrappers/obj-c/ODWPrivacyGuard.mm
  wrappers/obj-c/main.mm
Labels: enhancement
